apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-survey-app
  template:
    metadata:
      labels:
        app: student-survey-app
    spec:
      containers:
        - name: student-survey-app
          image: 851725518860.dkr.ecr.us-east-2.amazonaws.com/student-survey-app:latest
          ports:
            - containerPort: 8080
