apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
spec:
  selector:
    app: student-survey-app
  ports:
    - protocol: TCP
      port: 80      # Exposing port 80 on the LoadBalancer
      targetPort: 8080  # Port your Spring Boot app listens on inside the container
  type: LoadBalancer
